{
 "title": "CPU Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Temperature (Celcius)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_temperature_celsius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltages (Volt)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_voltage_volt{rail=\"3.3V Rail\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_voltage_volt{rail=\"5V Rail\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_voltage_volt{rail=\"12V Rail\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power (Watts)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(cpu_powers_watt[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}